--DB: farmra
--User: farmra_owner

--Table Creation Script
DO $TCS$
BEGIN

    DROP TABLE IF EXISTS node_data.measurements;
    DROP TABLE IF EXISTS node_data.nodes;
    DROP TABLE IF EXISTS node_data.gateways;
    DROP TABLE IF EXISTS user_data.users;

    --SCHEMA: user_data
    SET SEARCH_PATH to user_data;

    CREATE TABLE users
    (
        u_userId INTEGER GENERATED BY DEFAULT AS IDENTITY,
        u_fName VARCHAR(32) NOT NULL,
        u_lName VARCHAR(32) NOT NULL,
        u_email VARCHAR(64) UNIQUE NOT NULL,
        u_isAdmin BOOLEAN NOT NULL,
        
        CONSTRAINT users_pk PRIMARY KEY(u_usersId)
    );

    --SCHEMA: node_data
    SET SEARCH_PATH to node_data;

    CREATE TABLE devices
    (
        d_nodeId INTEGER GENERATED BY DEFAULT AS IDENTITY,
        d_gatewayId VARCHAR(12) NOT NULL,
        d_userId INTEGER NOT NULL,
        d_nodeName VARCHAR(32) NOT NULL,
        d_gpsLong FLOAT,
        d_gpsLat FLOAT,        
        

        CONSTRAINT devices_pk PRIMARY KEY(d_nodeId)
        CONSTRAINT unique_name_gid UNIQUE (d_gatewayId, d_nodeName)
        CONSTRAINT users_fk FOREIGN KEY(d_userId) 
                        REFERENCES user_data.users(u_userId)
    );


    CREATE TABLE measurements
    (
        m_time TIMESTAMPTZ NOT NULL,
        m_nodeID INTEGER NOT NULL,
        m_temperature DOUBLE PRECISION,
        m_moist INT,
        m_light INT,
        m_batt INT,
        
        CONSTRAINT measurements_fk FOREIGN KEY(m_nodeId) 
                        REFERENCES node_data.devices(d_nodeId)
    );

    SELECT create_hypertable('test_measurements', 'm_time');

END $TCS$;

--Add users and privileges
GRANT CONNECT ON DATABASE farmra TO user_lambda;
GRANT USAGE ON SCHEMA node_data TO user_lambda;
GRANT INSERT ON TABLE node_data.measurements TO user_lambda;

GRANT USAGE ON SCHEMA testing_grounds TO user_lambda;
GRANT INSERT ON TABLE testing_grounds.test_measurements TO user_lambda;
GRANT SELECT ON TABLE testing_grounds.nodes TO user_lambda;

GRANT CONNECT ON DATABASE farmra TO user_grafana;
GRANT USAGE ON SCHEMA node_data TO user_grafana;
GRANT SELECT ON TABLE node_data.measurements TO user_grafana;

GRANT USAGE ON SCHEMA testing_grounds TO user_grafana;
GRANT SELECT ON TABLE testing_grounds.test_measurements TO user_grafana;

--Initialization data
INSERT INTO user_data.users
(u_f_name, u_l_name, u_email, u_role)
VALUES
('farm', 'ra', 'untfarmra@gmail.com', 'admin');

INSERT INTO node_data.gateways
(g_id) 
VALUES 
('657d6f412cfcaf87');

INSERT INTO node_data.nodes
(n_name, g_id_fk, n_id)
VALUES
('node 1', '657d6f412cfcaf87', 1), ('node 2', '657d6f412cfcaf87', 2);
        
