--DB: farmra
--User: farmra_owner

--Table Creation Script
DO $TCS$
BEGIN

    DROP TABLE IF EXISTS node_data.measurements;
    DROP TABLE IF EXISTS node_data.devices;
    DROP TABLE IF EXISTS user_data.users;

    --SCHEMA: user_data
    SET SEARCH_PATH to user_data;

    CREATE TABLE users
    (
        u_userId INTEGER GENERATED BY DEFAULT AS IDENTITY,
        u_fName VARCHAR(32) NOT NULL,
        u_lName VARCHAR(32) NOT NULL,
        u_email VARCHAR(200) UNIQUE NOT NULL,
        u_isAdmin BOOLEAN NOT NULL,
        
        CONSTRAINT users_pk PRIMARY KEY(u_userId)
    );

    --SCHEMA: node_data
    SET SEARCH_PATH to node_data;

    CREATE TABLE devices
    (
        d_nodeId INTEGER GENERATED BY DEFAULT AS IDENTITY,
        d_gatewayId VARCHAR(32) NOT NULL,
        d_userId INTEGER NOT NULL,
        d_nodeName VARCHAR(32) NOT NULL,
        d_gpsLong FLOAT,
        d_gpsLat FLOAT,
        d_maxTemp INTEGER DEFAULT 100,        
        d_minTemp INTEGER DEFAULT 100,
        d_maxMoist INTEGER DEFAULT 2450,
        d_minMoist INTEGER DEFAULT 1900,

        CONSTRAINT devices_pk PRIMARY KEY(d_nodeId),
        CONSTRAINT unique_name_gid UNIQUE (d_gatewayId, d_nodeName),
        CONSTRAINT users_fk FOREIGN KEY(d_userId) 
                        REFERENCES user_data.users(u_userId)
    );

    CREATE TABLE measurements
    (
        m_time TIMESTAMPTZ NOT NULL,
        m_nodeID INTEGER NOT NULL,
        m_temperature DOUBLE PRECISION,
        m_moist INT,
        m_light INT,
        m_batt INT,
        
        CONSTRAINT measurements_fk FOREIGN KEY(m_nodeId) 
                        REFERENCES node_data.devices(d_nodeId)
    );
END $TCS$;

--Create hypertable and index
SELECT create_hypertable('measurements', 'm_time');
CREATE INDEX ON node_data.measurements (m_nodeID, m_time DESC);

--Add users and privileges
GRANT CONNECT ON DATABASE farmra TO user_lambda;
GRANT USAGE ON SCHEMA node_data TO user_lambda;
GRANT USAGE ON SCHEMA user_data TO user_lambda;
GRANT INSERT ON TABLE node_data.measurements TO user_lambda;
GRANT SELECT ON TABLE node_data.devices TO user_lambda;
GRANT SELECT ON TABLE user_data.users TO user_lambda;

GRANT CONNECT ON DATABASE farmra TO user_grafana;
GRANT USAGE ON SCHEMA node_data TO user_grafana;
GRANT SELECT ON TABLE user_data.users TO user_grafana;
GRANT SELECT ON TABLE node_data.devices TO user_grafana;
GRANT SELECT ON TABLE node_data.measurements TO user_grafana;

GRANT CONNECT ON DATABASE farmra TO user_flask;
GRANT USAGE ON SCHEMA node_data TO user_flask;
GRANT USAGE ON SCHEMA user_data TO user_flask;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE user_data.users TO user_flask;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE node_data.devices TO user_flask;
GRANT SELECT ON TABLE node_data.measurements TO user_flask;


--Initialization data
INSERT INTO user_data.users
(u_fName, u_lName, u_email, u_isAdmin, u_userId)
VALUES
('farm', 'ra', 'untfarmra@gmail.com', TRUE, 98),
('farmra', 'user', 'farmrauser@gmail.com', FALSE, 99);

--Inserts untfarmra@gmail.com in encrypted form
INSERT INTO user_data.users
(u_fName, u_lName, u_email, u_isAdmin, u_userId)
VALUES
('farm', 'ra', 'gAAAAABp2UPpgXH7r_PaM0Dg1kD351lFaiztxk5MGTahPNvpCpq85xX1BvM-HYlll9Yl2RrVWe6U5EBwUFnnmuVnKR_fwXF62JNz57oePkeHIL6fyxi4BHo=', TRUE, 1);

INSERT INTO node_data.devices
(d_nodeId, d_gatewayId, d_nodeName, d_userId )
VALUES
(1, '657d6f412cfcaf87', 'node_1', 2), (2, '657d6f412cfcaf87', 'node_2', 2);
