--DB: farmra

--SCHEMA: user_data

CREATE TABLE users
(
    u_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    u_name CHAR(32),
    
    CONSTRAINT users_pk PRIMARY KEY(u_id)
);

--SCHEMA: node_data

CREATE TABLE nodes
(
    n_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    u_id_fk INTEGER,
    n_plot_id INTEGER,
    n_wake_status BOOLEAN DEFAULT FALSE,
    
    CONSTRAINT nodes_pk PRIMARY KEY(n_id),
    CONSTRAINT nodes_fk FOREIGN KEY(u_id_fk) 
                    REFERENCES user_data.users(u_id)
);

--SCHEMA: node_data

CREATE TABLE measurements
(
    m_time TIMESTAMPTZ NOT NULL,
    n_id_fk INTEGER,
    m_temperature DOUBLE PRECISION,
    m_moisture DOUBLE PRECISION,
    m_light DOUBLE PRECISION,
    
    CONSTRAINT measurements_fk FOREIGN KEY(n_id_fk) 
                    REFERENCES nodes(n_id)
);

TRUNCATE TABLE measurements;
SELECT create_hypertable('measurements', 'm_time');
